# Generated by Django 5.0.3 on 2024-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=70)),
                ('data', models.DateTimeField()),
                ('nota_media', models.FloatField()),
                ('reviews', models.TextField(max_length=150)),
            ],
        ),
    ]
