# Generated by Django 5.0.3 on 2024-03-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='data',
            field=models.DateField(),
        ),
    ]
