# Generated by Django 5.0.3 on 2024-03-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_filmes_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='foto',
            field=models.ImageField(blank=True, upload_to='posters/'),
        ),
    ]
