# Generated by Django 5.0.3 on 2024-03-30 20:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_filmes_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmes',
            old_name='reviews',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='filmes',
            name='nota_media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=150)),
                ('nota', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 0), django.core.validators.MaxValueValidator(10, 0)])),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filmes')),
            ],
        ),
    ]
