# Generated by Django 5.0.3 on 2024-03-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reviews_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='usuario',
        ),
    ]
