# Generated by Django 5.0.3 on 2024-03-31 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_user_reviews_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='review',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.filmes'),
        ),
    ]
