# Generated by Django 5.0.3 on 2024-03-31 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_filmes_review_alter_reviews_filme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='avaliacoes',
            field=models.ManyToManyField(through='app.Reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
