# Generated by Django 5.0.3 on 2024-03-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_filmes_avaliacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='nota_media',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
